export default {
   employe: 'Сотрудники',
   normative: 'Нормативные документы',
   personal_products: 'Средства индивидуальной защиты',
   working_condition: 'Трудовые условия',
   positions: 'Должности',
   reports: 'Отчёты',
   users: 'Пользователи',
   organizations: 'Подразделения',
   table_number: 'Табельный номер',
   fio: 'Ф.И.О',
   work: 'Место работы',
   instruction: 'Иснтрукция',
   position: 'Должность',
   date_in_job: 'День принятия на работу ',
   name: 'Наименование',
   count: 'Количество',
   expiration_date: 'Срок',
   price: 'Цена',
   nomenclature: 'Номенклатура',
}